#gearman server host(can be multiple)
HOSTS_LIST:
 192.168.0.100:5000

#command run time out(unit s)
TIME_OUT:
 15

#task retry cycle
RETRY:
 2

#debug log(0/1,onely print data of job and run result, not do any thing)
DEBUG:
 0
