#gearman server host(can be multiple)
HOSTS_LIST:
 192.168.0.100:5000

#command run time out(unit s)
TIME_OUT:
 15

#task retry cycle
RETRY:
 2

#debug log(0/1)
#0:debug is off
#1:print log of run
#2:single-step debugging
DEBUG:
 0
